CREATE TABLE IF NOT EXISTS CLIENT
(
    IDT_CLIENT BIGSERIAL PRIMARY KEY,
    NAM_CLIENT VARCHAR(255) NOT NULL,
    LIMITE INT NOT NULL,
    BALANCE INT NOT NULL
);

CREATE TABLE IF NOT EXISTS MOVEMENTS
(
    IDT_TRANSACTION BIGSERIAL PRIMARY KEY,
    NUM_VALUE INT NOT NULL,
    NAM_TYPE VARCHAR(1) NOT NULL,
    NAM_DESC VARCHAR(10) NOT NULL,
    DAT_CREATION TIMESTAMP NOT NULL,
    IDT_CLIENT INT NOT NULL,
    FOREIGN KEY (IDT_CLIENT) REFERENCES CLIENT(IDT_CLIENT)
);

DO $$
BEGIN
  INSERT INTO CLIENT (nam_client, limite, balance)
  VALUES
    ('o barato sai caro', 1000 * 100, 0),
    ('zan corp ltda', 800 * 100, 0),
    ('les cruders', 10000 * 100, 0),
    ('padaria joia de cocaia', 100000 * 100, 0),
    ('kid mais', 5000 * 100, 0);
END; $$